name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - name: Build APK
        run: flutter build apk
      - name: Create Release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - Added feature X
            - Fixed issue Y
          draft: false
          prerelease: false
          # Upload the APK as an asset
          - name: Upload APK
            uses: actions/upload-artifact@v2
            with:
              name: my-app
              path: build/app/outputs/flutter-apk/app-release.apk
